SRC= \
	content/log.txt \
	content/hub.txt \
	content/get.txt \
	content/put.txt \
	content/truncate.txt \
	content/stat.txt \
	content/user.txt \
	content/pass.txt \
	content/help.txt \

bindata.go: $(SRC)
	go-bindata -pkg=help content